# -*- coding: utf-8 -*-
"""Model Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJKhKJjmBtpoTcwFHT4CMUDmWWiknXu0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
from google.colab import files
import os

# =========================
# 1) UPLOAD FILE
# =========================
uploaded = files.upload()

if not uploaded:
    raise ValueError("No file uploaded.")

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print(f"Loaded file: {file_name}")

# =========================
# 2) IDENTIFY COLUMNS
# =========================
label_col = "Given Label"
model_cols = [col for col in df.columns if col.endswith("_sentiment")]

if label_col not in df.columns:
    raise ValueError(f"Column '{label_col}' not found in file.")

if not model_cols:
    raise ValueError("No model columns found ending with '_sentiment'.")

print("Models found:")
for col in model_cols:
    print("-", col)

# Clean labels a bit
df[label_col] = df[label_col].astype(str).str.strip()
for col in model_cols:
    df[col] = df[col].astype(str).str.strip()

labels = sorted(df[label_col].dropna().unique())

# Make folder for charts
os.makedirs("charts", exist_ok=True)

# =========================
# 3) ANALYZE MODELS
# =========================
summary = []
per_label_results = []
confusion_data = []

comparison_df = df.copy()

for model in model_cols:
    y_true = df[label_col]
    y_pred = df[model]

    mask = y_true.notna() & y_pred.notna()
    y_true_clean = y_true[mask]
    y_pred_clean = y_pred[mask]

    acc = accuracy_score(y_true_clean, y_pred_clean)
    error = 1 - acc

    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        y_true_clean, y_pred_clean, average="macro", zero_division=0
    )
    precision_weighted, recall_weighted, f1_weighted, _ = precision_recall_fscore_support(
        y_true_clean, y_pred_clean, average="weighted", zero_division=0
    )

    summary.append({
        "model": model,
        "accuracy": acc,
        "error_rate": error,
        "precision_macro": precision_macro,
        "recall_macro": recall_macro,
        "f1_macro": f1_macro,
        "precision_weighted": precision_weighted,
        "recall_weighted": recall_weighted,
        "f1_weighted": f1_weighted,
        "total_rows_used": len(y_true_clean),
        "correct_count": int((y_true_clean == y_pred_clean).sum()),
        "wrong_count": int((y_true_clean != y_pred_clean).sum())
    })

    # Row-level correctness
    comparison_df[f"{model}_correct"] = (df[model] == df[label_col]).astype(int)

    # Per-label metrics
    p, r, f, support = precision_recall_fscore_support(
        y_true_clean, y_pred_clean, labels=labels, zero_division=0
    )

    for i, label in enumerate(labels):
        per_label_results.append({
            "model": model,
            "label": label,
            "precision": p[i],
            "recall": r[i],
            "f1": f[i],
            "support": support[i]
        })

    # Confusion matrix
    cm = confusion_matrix(y_true_clean, y_pred_clean, labels=labels)

    for i, true_label in enumerate(labels):
        for j, pred_label in enumerate(labels):
            confusion_data.append({
                "model": model,
                "true_label": true_label,
                "predicted_label": pred_label,
                "count": cm[i, j]
            })

# =========================
# 4) BUILD OUTPUT TABLES
# =========================
summary_df = pd.DataFrame(summary).sort_values(by="accuracy", ascending=False)
per_label_df = pd.DataFrame(per_label_results)
confusion_df = pd.DataFrame(confusion_data)

comparison_df["any_model_wrong"] = comparison_df[
    [f"{m}_correct" for m in model_cols]
].min(axis=1) == 0

disagreements_df = comparison_df[comparison_df["any_model_wrong"]].copy()

# =========================
# 5) SAVE CSV OUTPUTS
# =========================
summary_df.to_csv("model_summary.csv", index=False)
per_label_df.to_csv("per_label_metrics.csv", index=False)
confusion_df.to_csv("confusion_matrices.csv", index=False)
comparison_df.to_csv("row_level_comparison.csv", index=False)
disagreements_df.to_csv("disagreements_only.csv", index=False)

# =========================
# 6) CHARTS
# =========================

# ---- Chart 1: Accuracy by model
plt.figure(figsize=(12, 6))
plt.bar(summary_df["model"], summary_df["accuracy"])
plt.xticks(rotation=75, ha="right")
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.tight_layout()
plt.savefig("charts/model_accuracy.png", dpi=300)
plt.show()

# ---- Chart 2: Macro F1 by model
plt.figure(figsize=(12, 6))
plt.bar(summary_df["model"], summary_df["f1_macro"])
plt.xticks(rotation=75, ha="right")
plt.ylabel("Macro F1")
plt.title("Model Macro F1 Comparison")
plt.tight_layout()
plt.savefig("charts/model_macro_f1.png", dpi=300)
plt.show()

# ---- Chart 3: Error counts by model
plt.figure(figsize=(12, 6))
plt.bar(summary_df["model"], summary_df["wrong_count"])
plt.xticks(rotation=75, ha="right")
plt.ylabel("Wrong Predictions")
plt.title("Model Error Counts")
plt.tight_layout()
plt.savefig("charts/model_error_counts.png", dpi=300)
plt.show()

# ---- Chart 4: Per-label F1 grouped bar chart
pivot_f1 = per_label_df.pivot(index="model", columns="label", values="f1").fillna(0)

ax = pivot_f1.plot(kind="bar", figsize=(14, 7))
plt.xticks(rotation=75, ha="right")
plt.ylabel("F1 Score")
plt.title("Per-Label F1 Score by Model")
plt.legend(title="Label")
plt.tight_layout()
plt.savefig("charts/per_label_f1.png", dpi=300)
plt.show()

# ---- Chart 5: Confusion matrix heatmap for each model
for model in model_cols:
    model_cm = confusion_df[confusion_df["model"] == model]
    cm_matrix = model_cm.pivot(index="true_label", columns="predicted_label", values="count")
    cm_matrix = cm_matrix.reindex(index=labels, columns=labels, fill_value=0)

    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cm_matrix.values)

    ax.set_xticks(range(len(labels)))
    ax.set_yticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.set_yticklabels(labels)

    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    ax.set_title(f"Confusion Matrix: {model}")

    for i in range(len(labels)):
        for j in range(len(labels)):
            ax.text(j, i, int(cm_matrix.values[i, j]), ha="center", va="center")

    plt.tight_layout()

    safe_name = model.replace("/", "_").replace("\\", "_").replace(" ", "_")
    plt.savefig(f"charts/confusion_{safe_name}.png", dpi=300)
    plt.show()

# =========================
# 7) DISPLAY SUMMARY
# =========================
print("\n=== MODEL SUMMARY ===")
display(summary_df)

print("\n=== PER-LABEL METRICS ===")
display(per_label_df.head(15))

print("\nSaved files:")
print("- model_summary.csv")
print("- per_label_metrics.csv")
print("- confusion_matrices.csv")
print("- row_level_comparison.csv")
print("- disagreements_only.csv")
print("- charts/model_accuracy.png")
print("- charts/model_macro_f1.png")
print("- charts/model_error_counts.png")
print("- charts/per_label_f1.png")
print("- charts/confusion_<model>.png for each model")

# =========================
# 8) OPTIONAL DOWNLOADS
# =========================
files.download("model_summary.csv")
files.download("per_label_metrics.csv")
files.download("confusion_matrices.csv")
files.download("row_level_comparison.csv")
files.download("disagreements_only.csv")
files.download("charts/model_accuracy.png")
files.download("charts/model_macro_f1.png")
files.download("charts/model_error_counts.png")
files.download("charts/per_label_f1.png")